/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chapter12jni_HelloNative */

#ifndef _Included_chapter12jni_HelloNative
#define _Included_chapter12jni_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chapter12jni_HelloNative
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_chapter12jni_HelloNative_greeting
  (JNIEnv *, jclass);

/*
 * Class:     chapter12jni_HelloNative
 * Method:    print
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_chapter12jni_HelloNative_print
  (JNIEnv *, jclass, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
